export const GET_ALL_POKEMON = 'GET_ALL_POKEMON';
export const GET_ALL_POKEMON_SUCCESS = 'GET_ALL_POKEMON_SUCCESS';
export const GET_ALL_POKEMON_ERROR = 'GET_ALL_POKEMON_ERROR';

export const NEW_POKEDEX_MODAL = 'NEW_POKEDEX_MODAL';
export const NEW_POKEDEX_MODAL_SUCCESS = 'NEW_POKEDEX_MODAL_SUCCESS';
export const NEW_POKEDEX_MODAL_ERROR = 'NEW_POKEDEX_MODAL_ERROR';

export const CLEAR_POKEDEX_MODAL = 'CLEAR_POKEDEX_MODAL';
export const CLEAR_POKEDEX_MODAL_SUCCESS = 'CLEAR_POKEDEX_MODAL_SUCCESS';
export const CLEAR_POKEDEX_MODAL_ERROR = 'CLEAR_POKEDEX_MODAL_ERROR';

export const SELECT_POKEMON = 'SELECT_POKEMON'
export const SELECT_POKEMON_SUCCESS = 'SELECT_POKEMON_SUCCESS'
export const SELECT_POKEMON_ERROR = 'SELECT_POKEMON_ERROR'
